site_name: Eletta
site_url: https://unb-mds.github.io/Eletta/
docs_dir: Docs
nav:
  - ğŸ¡ Home: index.md
  - ğŸ“š DocumentaÃ§Ã£o:
      - ğŸ—‚ï¸ Arquitetura de Software: Arquitetura.md
      - ğŸ› ï¸ ProtÃ³tipo: Prototipo.md
      - ğŸ§© Sprints:
          - Sprint 0: Sprints/Sprint_0.md
          - Sprint 1: Sprints/Sprint_1.md
          - Sprint 2: Sprints/Sprint_2.md
          - Sprint 3: Sprints/Sprint_3.md
          - Sprint 4: Sprints/Sprint_4.md
          - Sprint 5: Sprints/Sprint_5.md
          - Sprint 6: Sprints/Sprint_6.md
          - Sprint 7: Sprints/Sprint_7.md
          - Sprint 8: Sprints/Sprint_8.md
          - Sprint 9: Sprints/Sprint_9.md
          - Sprint 10: Sprints/Sprint_10.md
          - Sprint 11: Sprints/Sprint_11.md
          - Sprint 12: Sprints/Sprint_12.md
      - ğŸ—ºï¸ Story Map e User Flow:
          - Story Map: StoryMap.md
          - User Flow: UserFlow.md
  - ğŸ“‹ Sobre o Projeto: Sobrenos.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/images/logo.png
  favicon: assets/icon/favicon.ico
  features:
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - search.suggest
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: deep orange

markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['./']
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unb-mds/2025-1-Squad06
    - icon: simple/miro
      link: https://miro.com/app/board/uXjVIJOVs_Y=/

copyright: Â© 2025 Eletta